### ISSUE TITLE
RPM build failure when building from source

### ISSUE THREAD

**Issue by Caleb-Shepard** [tgsachse/shellcuts#32]
![screenshot_20180310_084049](https://user-images.githubusercontent.com/10443116/37243241-38d0cf84-2444-11e8-9f7f-a9ad0e9b6876.png)

(Edit)
This is on a new Fedora 27 install with Python3 and zsh installed. The shell running in the screen cap is zsh with an active tmux session.

**Comment by tigressine** [comment]
rpmdev-setuptree is not available for ubuntu from what I've seen so I just manually assemble the tree in the latest version. Serves me right for trying to use a dependency for something so simple.

**Comment by tigressine** [comment]
Still can't build rpms on my system right now and I don't feel like fixing it at the moment. I'll get to it soon.

**Comment by tigressine** [comment]
Removing rpm installation process in 1.2.3
