### ISSUE TITLE
The `-l` option on `man` breaks macOS

### ISSUE THREAD

**Issue by excursus** [tgsachse/shellcuts#82]
https://github.com/tgsachse/shellcuts/blob/f1ec156daa5f66fa48265ca1ec51453401b2e266/source/core/commander.py#L152

**Comment by tigressine** [comment]
Next version of this project puts the manpage in a more typical location, so `man sc` will work instead of this little hack I had in the Python version. Will resolve this issue once I ship a distributable for MacOS.
